name: Build Project (Manual + Push)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Limpar cache npm
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist
